trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '21'
      architecture: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Use Java 21'

  - script: mvn clean verify
    displayName: 'Build and test with Maven'

- job: Job2
  steps:
  - script: echo This is Job2 - Java 21 ready
    displayName: 'Run a one-line script'
